## Pablo Valdunciel Sánchez 
### 7th October, 2019

Given two samples X and Y, compute the following distances:

- Euclidean
- Minkowsky with q=1 y q=3
- Mahalanobis

In [11]:
from scipy.spatial.distance import euclidean, minkowski, mahalanobis
import numpy as np

In [4]:
X = np.array([2.1, 3.1, 3.4, 1.9])
X

array([2.1, 3.1, 3.4, 1.9])

In [5]:
Y = np.array([1.2, 2, 1.7, 3.6])
Y

array([1.2, 2. , 1.7, 3.6])

In [6]:
S = np.array([[2, 0, 0, 0], 
              [0, 4, 0, 0],
              [0, 0, 4, 0],
              [0, 0, 0, 2]])
inv_S = np.linalg.inv(S)
inv_S

array([[0.5 , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.5 ]])

In [7]:
d_euclidean = euclidean(X,Y)

In [8]:
d_minkowsky_1 = minkowski(X,Y,1)
d_minkowsky_3 = minkowski(X,Y,3)

In [9]:
d_mahalanobis = mahalanobis(X, Y, inv_S)

In [10]:
print("Distances:" + 
      "\n- Euclidean: " + str(d_euclidean) +
      "\n- Minkowsky (q=1). " + str(d_minkowsky_1) +
      "\n- Minkowsky (q=3): " + str(d_minkowsky_3) + 
      "\n- Mahalanobis: " + str(d_mahalanobis))

Distances:
- Euclidean: 2.7928480087537886
- Minkowsky (q=1). 5.4
- Minkowsky (q=3): 2.282155548417709
- Mahalanobis: 1.6955824957813173
